name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    uses: erickfranca/shared-workflows/.github/workflows/build-and-push.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      service_name: node-shipping-service
      role_arn: ${{ vars.ROLE_ARN }}