name: CI

on:
  push:
    branches: [main]

jobs:
  security-scan:
    uses: erickfranca/shared-workflows/.github/workflows/security-scan.yml@main
  
  build:
    needs: security-scan
    uses: erickfranca/shared-workflows/.github/workflows/build-and-push.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      service_name: node-shipping-service
      role_arn: ${{ vars.ROLE_ARN }}

  update-manifests:
    needs: build
    uses: erickfranca/shared-workflows/.github/workflows/update-manifests.yml@main
    with:
      service_name: node-shipping-service
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets:
      MANIFESTS_REPO_PAT: ${{ secrets.MANIFESTS_REPO_PAT }}